### ISSUE TITLE
Stats endpoint 

### ISSUE THREAD

**Issue by zzarcon** [zzarcon/github-spy-backend#1]
Proposal:
#### Request

**GET** `api/stats/REPOSITORY_ID`
#### Response

``` json
{
    "stat": {
        "id": "1234",
        "total_stars": 120,
        "new_stars": 10,
        "last_time_checked": "01/08/2015 10:10:10"
    }
}
```
#### Request

**PUT** `api/stats/REPOSITORY_ID`
#### Response

The response will be the same as the **GET** one but clearing the `new_stars` and updating the date.

``` json
{
    "stat": {
        "id": "1234",
        "total_stars": 120,
        "new_stars": 0,
        "last_time_checked": "Backend current time"
    }
}
```

**Comment by zzarcon** [comment]
cc/ @joanromano

**Comment by joanromano** [comment]
@zzarcon do I need to send the object in the PUT request?

**Comment by zzarcon** [comment]
Should not be mandatory, I will only check the **last_time_checked** value of the request

**Comment by joanromano** [comment]
But if I'm setting that property to the current time isn't it a bit redudant?

**Comment by zzarcon** [comment]
Yes, its quite explicit and redundant... what you prefer for clear the stats?

**Comment by joanromano** [comment]
Just a PUT with the repo ID... does that make sense?

**Comment by zzarcon** [comment]
Yup i will update the spec

**Comment by zzarcon** [comment]
DEPRECATED --> https://github.com/Git-spy/git-spy-node/issues/2
